### ISSUE TITLE
About how to make patches trimmed in visualization

### ISSUE THREAD

**Issue by Mingyu-Zheng** [guohaoxiang/ComplexGen#9]
Hi and thank you for the great work!
I have a question about "Phase 3: Geometric refinement" and visualization. It's mentioned in the article.

> Model visualization. The optimized B-Rep model can be converted to specific formats for CAD software consumption. To visualize the whole models, we develop a simple procedure that extracts mesh models from the B-Rep chain complex: we use curve loops to cut their incident patches triangulated and obtain a collection of trimmed patches. The final patches, curves and corners form a mesh model that follows the predicted topology and fits to the input geometry. Examples of diverse complexities are shown in Figs. 1, 6, 8 and 10 and the supplemental document. 

As shown in the figure below, after I run the third stage, the edge of some patches have not been cut  in my visualization results. It can be seen that the two planes at the center and bottom of the nut have exceeded parts.
![图片](https://user-images.githubusercontent.com/73884322/219296505-0e95a2b2-6761-4835-b899-028e52b57325.png)

I want to know how to get the same result as shown in your paper.
![图片](https://user-images.githubusercontent.com/73884322/219296908-575b3b1d-7192-457b-a317-c1278a15d377.png)

Thanks!

**Comment by guohaoxiang** [comment]
Hi, Azaan, thanks for your interests on our work. In the trimming step, we firstly crop open curves with its neighoring corners. Then for each patch, we formulate all of its neighorbor curves and corners into loops according to their topological connectivity, then crop the patch with these loops. All the procedures above are geometric operations which can be implemented with geometric libraries like CGAL or libigl. We does not release this part of code because our implementation is numerically unstable for some cases.
